services:
  catalogdb:
    image: postgres:13-alpine

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Microservices/Catalog/Catalog.API/Dockerfile

volumes:
  postgres_catalog:
